/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddBookResponseData
 */
export interface AddBookResponseData {
    /**
     * 
     * @type {number}
     * @memberof AddBookResponseData
     */
    id?: number;
}

/**
 * Check if a given object implements the AddBookResponseData interface.
 */
export function instanceOfAddBookResponseData(value: object): value is AddBookResponseData {
    return true;
}

export function AddBookResponseDataFromJSON(json: any): AddBookResponseData {
    return AddBookResponseDataFromJSONTyped(json, false);
}

export function AddBookResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddBookResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AddBookResponseDataToJSON(json: any): AddBookResponseData {
    return AddBookResponseDataToJSONTyped(json, false);
}

export function AddBookResponseDataToJSONTyped(value?: AddBookResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

