/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleInfo
 */
export interface ArticleInfo {
    /**
     * 
     * @type {number}
     * @memberof ArticleInfo
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleInfo
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleInfo
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof ArticleInfo
     */
    authorID: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleInfo
     */
    status: ArticleInfoStatusEnum;
}


/**
 * @export
 */
export const ArticleInfoStatusEnum = {
    Published: 'published',
    Unpublished: 'unpublished'
} as const;
export type ArticleInfoStatusEnum = typeof ArticleInfoStatusEnum[keyof typeof ArticleInfoStatusEnum];


/**
 * Check if a given object implements the ArticleInfo interface.
 */
export function instanceOfArticleInfo(value: object): value is ArticleInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('authorID' in value) || value['authorID'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ArticleInfoFromJSON(json: any): ArticleInfo {
    return ArticleInfoFromJSONTyped(json, false);
}

export function ArticleInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'content': json['content'],
        'authorID': json['authorID'],
        'status': json['status'],
    };
}

export function ArticleInfoToJSON(json: any): ArticleInfo {
    return ArticleInfoToJSONTyped(json, false);
}

export function ArticleInfoToJSONTyped(value?: ArticleInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'authorID': value['authorID'],
        'status': value['status'],
    };
}

