/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorInfo
 */
export interface AuthorInfo {
    /**
     * 
     * @type {number}
     * @memberof AuthorInfo
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AuthorInfo
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorInfo
     */
    lastName?: string;
}

/**
 * Check if a given object implements the AuthorInfo interface.
 */
export function instanceOfAuthorInfo(value: object): value is AuthorInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    return true;
}

export function AuthorInfoFromJSON(json: any): AuthorInfo {
    return AuthorInfoFromJSONTyped(json, false);
}

export function AuthorInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
    };
}

export function AuthorInfoToJSON(json: any): AuthorInfo {
    return AuthorInfoToJSONTyped(json, false);
}

export function AuthorInfoToJSONTyped(value?: AuthorInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

