/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorData
 */
export interface AuthorData {
    /**
     * 
     * @type {number}
     * @memberof AuthorData
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AuthorData
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorData
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorData
     */
    avatarPath?: string;
}

/**
 * Check if a given object implements the AuthorData interface.
 */
export function instanceOfAuthorData(value: object): value is AuthorData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    return true;
}

export function AuthorDataFromJSON(json: any): AuthorData {
    return AuthorDataFromJSONTyped(json, false);
}

export function AuthorDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'description': json['description'] == null ? undefined : json['description'],
        'avatarPath': json['avatarPath'] == null ? undefined : json['avatarPath'],
    };
}

export function AuthorDataToJSON(json: any): AuthorData {
    return AuthorDataToJSONTyped(json, false);
}

export function AuthorDataToJSONTyped(value?: AuthorData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'description': value['description'],
        'avatarPath': value['avatarPath'],
    };
}

