/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorInfo } from './AuthorInfo';
import {
    AuthorInfoFromJSON,
    AuthorInfoFromJSONTyped,
    AuthorInfoToJSON,
    AuthorInfoToJSONTyped,
} from './AuthorInfo';

/**
 * 
 * @export
 * @interface BookInLibrary
 */
export interface BookInLibrary {
    /**
     * 
     * @type {number}
     * @memberof BookInLibrary
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BookInLibrary
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof BookInLibrary
     */
    coverPath?: string;
    /**
     * 
     * @type {Array<AuthorInfo>}
     * @memberof BookInLibrary
     */
    authors: Array<AuthorInfo>;
    /**
     * 
     * @type {number}
     * @memberof BookInLibrary
     */
    starCount: number;
    /**
     * 
     * @type {string}
     * @memberof BookInLibrary
     */
    readingStatus: BookInLibraryReadingStatusEnum;
}


/**
 * @export
 */
export const BookInLibraryReadingStatusEnum = {
    InProgress: 'inProgress',
    Finished: 'finished',
    Planned: 'planned'
} as const;
export type BookInLibraryReadingStatusEnum = typeof BookInLibraryReadingStatusEnum[keyof typeof BookInLibraryReadingStatusEnum];


/**
 * Check if a given object implements the BookInLibrary interface.
 */
export function instanceOfBookInLibrary(value: object): value is BookInLibrary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('authors' in value) || value['authors'] === undefined) return false;
    if (!('starCount' in value) || value['starCount'] === undefined) return false;
    if (!('readingStatus' in value) || value['readingStatus'] === undefined) return false;
    return true;
}

export function BookInLibraryFromJSON(json: any): BookInLibrary {
    return BookInLibraryFromJSONTyped(json, false);
}

export function BookInLibraryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookInLibrary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'coverPath': json['coverPath'] == null ? undefined : json['coverPath'],
        'authors': ((json['authors'] as Array<any>).map(AuthorInfoFromJSON)),
        'starCount': json['starCount'],
        'readingStatus': json['readingStatus'],
    };
}

export function BookInLibraryToJSON(json: any): BookInLibrary {
    return BookInLibraryToJSONTyped(json, false);
}

export function BookInLibraryToJSONTyped(value?: BookInLibrary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'coverPath': value['coverPath'],
        'authors': ((value['authors'] as Array<any>).map(AuthorInfoToJSON)),
        'starCount': value['starCount'],
        'readingStatus': value['readingStatus'],
    };
}

