/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryInfo } from './CategoryInfo';
import {
    CategoryInfoFromJSON,
    CategoryInfoFromJSONTyped,
    CategoryInfoToJSON,
    CategoryInfoToJSONTyped,
} from './CategoryInfo';
import type { AuthorInfo } from './AuthorInfo';
import {
    AuthorInfoFromJSON,
    AuthorInfoFromJSONTyped,
    AuthorInfoToJSON,
    AuthorInfoToJSONTyped,
} from './AuthorInfo';
import type { FeedbackInfo } from './FeedbackInfo';
import {
    FeedbackInfoFromJSON,
    FeedbackInfoFromJSONTyped,
    FeedbackInfoToJSON,
    FeedbackInfoToJSONTyped,
} from './FeedbackInfo';

/**
 * 
 * @export
 * @interface BookInfo
 */
export interface BookInfo {
    /**
     * 
     * @type {number}
     * @memberof BookInfo
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    coverPath: string;
    /**
     * 
     * @type {Array<AuthorInfo>}
     * @memberof BookInfo
     */
    authors: Array<AuthorInfo>;
    /**
     * 
     * @type {number}
     * @memberof BookInfo
     */
    starCount: number;
    /**
     * 
     * @type {Array<FeedbackInfo>}
     * @memberof BookInfo
     */
    feedback?: Array<FeedbackInfo>;
    /**
     * 
     * @type {Array<CategoryInfo>}
     * @memberof BookInfo
     */
    categories: Array<CategoryInfo>;
}

/**
 * Check if a given object implements the BookInfo interface.
 */
export function instanceOfBookInfo(value: object): value is BookInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('coverPath' in value) || value['coverPath'] === undefined) return false;
    if (!('authors' in value) || value['authors'] === undefined) return false;
    if (!('starCount' in value) || value['starCount'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    return true;
}

export function BookInfoFromJSON(json: any): BookInfo {
    return BookInfoFromJSONTyped(json, false);
}

export function BookInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'coverPath': json['coverPath'],
        'authors': ((json['authors'] as Array<any>).map(AuthorInfoFromJSON)),
        'starCount': json['starCount'],
        'feedback': json['feedback'] == null ? undefined : ((json['feedback'] as Array<any>).map(FeedbackInfoFromJSON)),
        'categories': ((json['categories'] as Array<any>).map(CategoryInfoFromJSON)),
    };
}

export function BookInfoToJSON(json: any): BookInfo {
    return BookInfoToJSONTyped(json, false);
}

export function BookInfoToJSONTyped(value?: BookInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'coverPath': value['coverPath'],
        'authors': ((value['authors'] as Array<any>).map(AuthorInfoToJSON)),
        'starCount': value['starCount'],
        'feedback': value['feedback'] == null ? undefined : ((value['feedback'] as Array<any>).map(FeedbackInfoToJSON)),
        'categories': ((value['categories'] as Array<any>).map(CategoryInfoToJSON)),
    };
}

