/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryInfo
 */
export interface CategoryInfo {
    /**
     * 
     * @type {number}
     * @memberof CategoryInfo
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryInfo
     */
    category: string;
}

/**
 * Check if a given object implements the CategoryInfo interface.
 */
export function instanceOfCategoryInfo(value: object): value is CategoryInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function CategoryInfoFromJSON(json: any): CategoryInfo {
    return CategoryInfoFromJSONTyped(json, false);
}

export function CategoryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'category': json['category'],
    };
}

export function CategoryInfoToJSON(json: any): CategoryInfo {
    return CategoryInfoToJSONTyped(json, false);
}

export function CategoryInfoToJSONTyped(value?: CategoryInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'category': value['category'],
    };
}

