/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeReadingStatusRequest
 */
export interface ChangeReadingStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof ChangeReadingStatusRequest
     */
    readingStatus: ChangeReadingStatusRequestReadingStatusEnum;
}


/**
 * @export
 */
export const ChangeReadingStatusRequestReadingStatusEnum = {
    InProgress: 'inProgress',
    Finished: 'finished',
    Planned: 'planned'
} as const;
export type ChangeReadingStatusRequestReadingStatusEnum = typeof ChangeReadingStatusRequestReadingStatusEnum[keyof typeof ChangeReadingStatusRequestReadingStatusEnum];


/**
 * Check if a given object implements the ChangeReadingStatusRequest interface.
 */
export function instanceOfChangeReadingStatusRequest(value: object): value is ChangeReadingStatusRequest {
    if (!('readingStatus' in value) || value['readingStatus'] === undefined) return false;
    return true;
}

export function ChangeReadingStatusRequestFromJSON(json: any): ChangeReadingStatusRequest {
    return ChangeReadingStatusRequestFromJSONTyped(json, false);
}

export function ChangeReadingStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeReadingStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'readingStatus': json['readingStatus'],
    };
}

export function ChangeReadingStatusRequestToJSON(json: any): ChangeReadingStatusRequest {
    return ChangeReadingStatusRequestToJSONTyped(json, false);
}

export function ChangeReadingStatusRequestToJSONTyped(value?: ChangeReadingStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'readingStatus': value['readingStatus'],
    };
}

