/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeUserRoleRequest
 */
export interface ChangeUserRoleRequest {
    /**
     * 
     * @type {string}
     * @memberof ChangeUserRoleRequest
     */
    role: ChangeUserRoleRequestRoleEnum;
}


/**
 * @export
 */
export const ChangeUserRoleRequestRoleEnum = {
    User: 'user',
    Editor: 'editor'
} as const;
export type ChangeUserRoleRequestRoleEnum = typeof ChangeUserRoleRequestRoleEnum[keyof typeof ChangeUserRoleRequestRoleEnum];


/**
 * Check if a given object implements the ChangeUserRoleRequest interface.
 */
export function instanceOfChangeUserRoleRequest(value: object): value is ChangeUserRoleRequest {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ChangeUserRoleRequestFromJSON(json: any): ChangeUserRoleRequest {
    return ChangeUserRoleRequestFromJSONTyped(json, false);
}

export function ChangeUserRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeUserRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
    };
}

export function ChangeUserRoleRequestToJSON(json: any): ChangeUserRoleRequest {
    return ChangeUserRoleRequestToJSONTyped(json, false);
}

export function ChangeUserRoleRequestToJSONTyped(value?: ChangeUserRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
    };
}

