/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckBookInLibraryResponseData
 */
export interface CheckBookInLibraryResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof CheckBookInLibraryResponseData
     */
    contains: boolean;
}

/**
 * Check if a given object implements the CheckBookInLibraryResponseData interface.
 */
export function instanceOfCheckBookInLibraryResponseData(value: object): value is CheckBookInLibraryResponseData {
    if (!('contains' in value) || value['contains'] === undefined) return false;
    return true;
}

export function CheckBookInLibraryResponseDataFromJSON(json: any): CheckBookInLibraryResponseData {
    return CheckBookInLibraryResponseDataFromJSONTyped(json, false);
}

export function CheckBookInLibraryResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckBookInLibraryResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'contains': json['contains'],
    };
}

export function CheckBookInLibraryResponseDataToJSON(json: any): CheckBookInLibraryResponseData {
    return CheckBookInLibraryResponseDataToJSONTyped(json, false);
}

export function CheckBookInLibraryResponseDataToJSONTyped(value?: CheckBookInLibraryResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contains': value['contains'],
    };
}

