/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckBookInLibrary200Response
 */
export interface CheckBookInLibrary200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CheckBookInLibrary200Response
     */
    contains?: boolean;
}

/**
 * Check if a given object implements the CheckBookInLibrary200Response interface.
 */
export function instanceOfCheckBookInLibrary200Response(value: object): value is CheckBookInLibrary200Response {
    return true;
}

export function CheckBookInLibrary200ResponseFromJSON(json: any): CheckBookInLibrary200Response {
    return CheckBookInLibrary200ResponseFromJSONTyped(json, false);
}

export function CheckBookInLibrary200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckBookInLibrary200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'contains': json['contains'] == null ? undefined : json['contains'],
    };
}

export function CheckBookInLibrary200ResponseToJSON(json: any): CheckBookInLibrary200Response {
    return CheckBookInLibrary200ResponseToJSONTyped(json, false);
}

export function CheckBookInLibrary200ResponseToJSONTyped(value?: CheckBookInLibrary200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contains': value['contains'],
    };
}

