/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAuthorResponseData
 */
export interface CreateAuthorResponseData {
    /**
     * 
     * @type {number}
     * @memberof CreateAuthorResponseData
     */
    id: number;
}

/**
 * Check if a given object implements the CreateAuthorResponseData interface.
 */
export function instanceOfCreateAuthorResponseData(value: object): value is CreateAuthorResponseData {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreateAuthorResponseDataFromJSON(json: any): CreateAuthorResponseData {
    return CreateAuthorResponseDataFromJSONTyped(json, false);
}

export function CreateAuthorResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAuthorResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateAuthorResponseDataToJSON(json: any): CreateAuthorResponseData {
    return CreateAuthorResponseDataToJSONTyped(json, false);
}

export function CreateAuthorResponseDataToJSONTyped(value?: CreateAuthorResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

