/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAuthorRequest
 */
export interface CreateAuthorRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateAuthorRequest interface.
 */
export function instanceOfCreateAuthorRequest(value: object): value is CreateAuthorRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    return true;
}

export function CreateAuthorRequestFromJSON(json: any): CreateAuthorRequest {
    return CreateAuthorRequestFromJSONTyped(json, false);
}

export function CreateAuthorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAuthorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateAuthorRequestToJSON(json: any): CreateAuthorRequest {
    return CreateAuthorRequestToJSONTyped(json, false);
}

export function CreateAuthorRequestToJSONTyped(value?: CreateAuthorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'description': value['description'],
    };
}

