/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateArticleResponseData
 */
export interface CreateArticleResponseData {
    /**
     * 
     * @type {number}
     * @memberof CreateArticleResponseData
     */
    id?: number;
}

/**
 * Check if a given object implements the CreateArticleResponseData interface.
 */
export function instanceOfCreateArticleResponseData(value: object): value is CreateArticleResponseData {
    return true;
}

export function CreateArticleResponseDataFromJSON(json: any): CreateArticleResponseData {
    return CreateArticleResponseDataFromJSONTyped(json, false);
}

export function CreateArticleResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateArticleResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CreateArticleResponseDataToJSON(json: any): CreateArticleResponseData {
    return CreateArticleResponseDataToJSONTyped(json, false);
}

export function CreateArticleResponseDataToJSONTyped(value?: CreateArticleResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

