/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateArticleRequest
 */
export interface CreateArticleRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateArticleRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateArticleRequest
     */
    content: string;
}

/**
 * Check if a given object implements the CreateArticleRequest interface.
 */
export function instanceOfCreateArticleRequest(value: object): value is CreateArticleRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateArticleRequestFromJSON(json: any): CreateArticleRequest {
    return CreateArticleRequestFromJSONTyped(json, false);
}

export function CreateArticleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateArticleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
    };
}

export function CreateArticleRequestToJSON(json: any): CreateArticleRequest {
    return CreateArticleRequestToJSONTyped(json, false);
}

export function CreateArticleRequestToJSONTyped(value?: CreateArticleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

