/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditUserInfoRequest
 */
export interface EditUserInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof EditUserInfoRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof EditUserInfoRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof EditUserInfoRequest
     */
    avatarPath?: string;
}

/**
 * Check if a given object implements the EditUserInfoRequest interface.
 */
export function instanceOfEditUserInfoRequest(value: object): value is EditUserInfoRequest {
    return true;
}

export function EditUserInfoRequestFromJSON(json: any): EditUserInfoRequest {
    return EditUserInfoRequestFromJSONTyped(json, false);
}

export function EditUserInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditUserInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'avatarPath': json['avatarPath'] == null ? undefined : json['avatarPath'],
    };
}

export function EditUserInfoRequestToJSON(json: any): EditUserInfoRequest {
    return EditUserInfoRequestToJSONTyped(json, false);
}

export function EditUserInfoRequestToJSONTyped(value?: EditUserInfoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'avatarPath': value['avatarPath'],
    };
}

