/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfo } from './UserInfo';
import {
    UserInfoFromJSON,
    UserInfoFromJSONTyped,
    UserInfoToJSON,
    UserInfoToJSONTyped,
} from './UserInfo';

/**
 * 
 * @export
 * @interface GetAuthorizedUserResponseData
 */
export interface GetAuthorizedUserResponseData {
    /**
     * 
     * @type {UserInfo}
     * @memberof GetAuthorizedUserResponseData
     */
    user: UserInfo;
}

/**
 * Check if a given object implements the GetAuthorizedUserResponseData interface.
 */
export function instanceOfGetAuthorizedUserResponseData(value: object): value is GetAuthorizedUserResponseData {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function GetAuthorizedUserResponseDataFromJSON(json: any): GetAuthorizedUserResponseData {
    return GetAuthorizedUserResponseDataFromJSONTyped(json, false);
}

export function GetAuthorizedUserResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAuthorizedUserResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserInfoFromJSON(json['user']),
    };
}

export function GetAuthorizedUserResponseDataToJSON(json: any): GetAuthorizedUserResponseData {
    return GetAuthorizedUserResponseDataToJSONTyped(json, false);
}

export function GetAuthorizedUserResponseDataToJSONTyped(value?: GetAuthorizedUserResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserInfoToJSON(value['user']),
    };
}

