/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorInfo } from './AuthorInfo';
import {
    AuthorInfoFromJSON,
    AuthorInfoFromJSONTyped,
    AuthorInfoToJSON,
    AuthorInfoToJSONTyped,
} from './AuthorInfo';

/**
 * 
 * @export
 * @interface GetAuthorInfoResponseData
 */
export interface GetAuthorInfoResponseData {
    /**
     * 
     * @type {AuthorInfo}
     * @memberof GetAuthorInfoResponseData
     */
    author?: AuthorInfo;
}

/**
 * Check if a given object implements the GetAuthorInfoResponseData interface.
 */
export function instanceOfGetAuthorInfoResponseData(value: object): value is GetAuthorInfoResponseData {
    return true;
}

export function GetAuthorInfoResponseDataFromJSON(json: any): GetAuthorInfoResponseData {
    return GetAuthorInfoResponseDataFromJSONTyped(json, false);
}

export function GetAuthorInfoResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAuthorInfoResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : AuthorInfoFromJSON(json['author']),
    };
}

export function GetAuthorInfoResponseDataToJSON(json: any): GetAuthorInfoResponseData {
    return GetAuthorInfoResponseDataToJSONTyped(json, false);
}

export function GetAuthorInfoResponseDataToJSONTyped(value?: GetAuthorInfoResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': AuthorInfoToJSON(value['author']),
    };
}

