/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleInfo } from './ArticleInfo';
import {
    ArticleInfoFromJSON,
    ArticleInfoFromJSONTyped,
    ArticleInfoToJSON,
    ArticleInfoToJSONTyped,
} from './ArticleInfo';

/**
 * 
 * @export
 * @interface GetArticleResponseData
 */
export interface GetArticleResponseData {
    /**
     * 
     * @type {ArticleInfo}
     * @memberof GetArticleResponseData
     */
    article?: ArticleInfo;
}

/**
 * Check if a given object implements the GetArticleResponseData interface.
 */
export function instanceOfGetArticleResponseData(value: object): value is GetArticleResponseData {
    return true;
}

export function GetArticleResponseDataFromJSON(json: any): GetArticleResponseData {
    return GetArticleResponseDataFromJSONTyped(json, false);
}

export function GetArticleResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetArticleResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'article': json['article'] == null ? undefined : ArticleInfoFromJSON(json['article']),
    };
}

export function GetArticleResponseDataToJSON(json: any): GetArticleResponseData {
    return GetArticleResponseDataToJSONTyped(json, false);
}

export function GetArticleResponseDataToJSONTyped(value?: GetArticleResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article': ArticleInfoToJSON(value['article']),
    };
}

