/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookInfo } from './BookInfo';
import {
    BookInfoFromJSON,
    BookInfoFromJSONTyped,
    BookInfoToJSON,
    BookInfoToJSONTyped,
} from './BookInfo';

/**
 * 
 * @export
 * @interface GetBookInfoResponseData
 */
export interface GetBookInfoResponseData {
    /**
     * 
     * @type {BookInfo}
     * @memberof GetBookInfoResponseData
     */
    book: BookInfo;
}

/**
 * Check if a given object implements the GetBookInfoResponseData interface.
 */
export function instanceOfGetBookInfoResponseData(value: object): value is GetBookInfoResponseData {
    if (!('book' in value) || value['book'] === undefined) return false;
    return true;
}

export function GetBookInfoResponseDataFromJSON(json: any): GetBookInfoResponseData {
    return GetBookInfoResponseDataFromJSONTyped(json, false);
}

export function GetBookInfoResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBookInfoResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'book': BookInfoFromJSON(json['book']),
    };
}

export function GetBookInfoResponseDataToJSON(json: any): GetBookInfoResponseData {
    return GetBookInfoResponseDataToJSONTyped(json, false);
}

export function GetBookInfoResponseDataToJSONTyped(value?: GetBookInfoResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'book': BookInfoToJSON(value['book']),
    };
}

