/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFileResponseData
 */
export interface GetFileResponseData {
    /**
     * 
     * @type {Blob}
     * @memberof GetFileResponseData
     */
    file: Blob;
}

/**
 * Check if a given object implements the GetFileResponseData interface.
 */
export function instanceOfGetFileResponseData(value: object): value is GetFileResponseData {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function GetFileResponseDataFromJSON(json: any): GetFileResponseData {
    return GetFileResponseDataFromJSONTyped(json, false);
}

export function GetFileResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFileResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function GetFileResponseDataToJSON(json: any): GetFileResponseData {
    return GetFileResponseDataToJSONTyped(json, false);
}

export function GetFileResponseDataToJSONTyped(value?: GetFileResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
    };
}

