/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfo } from './UserInfo';
import {
    UserInfoFromJSON,
    UserInfoFromJSONTyped,
    UserInfoToJSON,
    UserInfoToJSONTyped,
} from './UserInfo';

/**
 * 
 * @export
 * @interface GetUserInfoResponseData
 */
export interface GetUserInfoResponseData {
    /**
     * 
     * @type {UserInfo}
     * @memberof GetUserInfoResponseData
     */
    user?: UserInfo;
}

/**
 * Check if a given object implements the GetUserInfoResponseData interface.
 */
export function instanceOfGetUserInfoResponseData(value: object): value is GetUserInfoResponseData {
    return true;
}

export function GetUserInfoResponseDataFromJSON(json: any): GetUserInfoResponseData {
    return GetUserInfoResponseDataFromJSONTyped(json, false);
}

export function GetUserInfoResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserInfoResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : UserInfoFromJSON(json['user']),
    };
}

export function GetUserInfoResponseDataToJSON(json: any): GetUserInfoResponseData {
    return GetUserInfoResponseDataToJSONTyped(json, false);
}

export function GetUserInfoResponseDataToJSONTyped(value?: GetUserInfoResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserInfoToJSON(value['user']),
    };
}

