/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookInLibrary } from './BookInLibrary';
import {
    BookInLibraryFromJSON,
    BookInLibraryFromJSONTyped,
    BookInLibraryToJSON,
    BookInLibraryToJSONTyped,
} from './BookInLibrary';

/**
 * 
 * @export
 * @interface ListLibraryBooksByStatusResponseData
 */
export interface ListLibraryBooksByStatusResponseData {
    /**
     * 
     * @type {Array<BookInLibrary>}
     * @memberof ListLibraryBooksByStatusResponseData
     */
    books: Array<BookInLibrary>;
    /**
     * 
     * @type {number}
     * @memberof ListLibraryBooksByStatusResponseData
     */
    totalNumber: number;
}

/**
 * Check if a given object implements the ListLibraryBooksByStatusResponseData interface.
 */
export function instanceOfListLibraryBooksByStatusResponseData(value: object): value is ListLibraryBooksByStatusResponseData {
    if (!('books' in value) || value['books'] === undefined) return false;
    if (!('totalNumber' in value) || value['totalNumber'] === undefined) return false;
    return true;
}

export function ListLibraryBooksByStatusResponseDataFromJSON(json: any): ListLibraryBooksByStatusResponseData {
    return ListLibraryBooksByStatusResponseDataFromJSONTyped(json, false);
}

export function ListLibraryBooksByStatusResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListLibraryBooksByStatusResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'books': ((json['books'] as Array<any>).map(BookInLibraryFromJSON)),
        'totalNumber': json['totalNumber'],
    };
}

export function ListLibraryBooksByStatusResponseDataToJSON(json: any): ListLibraryBooksByStatusResponseData {
    return ListLibraryBooksByStatusResponseDataToJSONTyped(json, false);
}

export function ListLibraryBooksByStatusResponseDataToJSONTyped(value?: ListLibraryBooksByStatusResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'books': ((value['books'] as Array<any>).map(BookInLibraryToJSON)),
        'totalNumber': value['totalNumber'],
    };
}

