/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookData } from './BookData';
import {
    BookDataFromJSON,
    BookDataFromJSONTyped,
    BookDataToJSON,
    BookDataToJSONTyped,
} from './BookData';

/**
 * 
 * @export
 * @interface ListLibraryBooksResponseData
 */
export interface ListLibraryBooksResponseData {
    /**
     * 
     * @type {Array<BookData>}
     * @memberof ListLibraryBooksResponseData
     */
    books?: Array<BookData>;
}

/**
 * Check if a given object implements the ListLibraryBooksResponseData interface.
 */
export function instanceOfListLibraryBooksResponseData(value: object): value is ListLibraryBooksResponseData {
    return true;
}

export function ListLibraryBooksResponseDataFromJSON(json: any): ListLibraryBooksResponseData {
    return ListLibraryBooksResponseDataFromJSONTyped(json, false);
}

export function ListLibraryBooksResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListLibraryBooksResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'books': json['books'] == null ? undefined : ((json['books'] as Array<any>).map(BookDataFromJSON)),
    };
}

export function ListLibraryBooksResponseDataToJSON(json: any): ListLibraryBooksResponseData {
    return ListLibraryBooksResponseDataToJSONTyped(json, false);
}

export function ListLibraryBooksResponseDataToJSONTyped(value?: ListLibraryBooksResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'books': value['books'] == null ? undefined : ((value['books'] as Array<any>).map(BookDataToJSON)),
    };
}

