/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorData } from './AuthorData';
import {
    AuthorDataFromJSON,
    AuthorDataFromJSONTyped,
    AuthorDataToJSON,
    AuthorDataToJSONTyped,
} from './AuthorData';

/**
 * 
 * @export
 * @interface ListAuthorsResponseData
 */
export interface ListAuthorsResponseData {
    /**
     * 
     * @type {Array<AuthorData>}
     * @memberof ListAuthorsResponseData
     */
    authors?: Array<AuthorData>;
}

/**
 * Check if a given object implements the ListAuthorsResponseData interface.
 */
export function instanceOfListAuthorsResponseData(value: object): value is ListAuthorsResponseData {
    return true;
}

export function ListAuthorsResponseDataFromJSON(json: any): ListAuthorsResponseData {
    return ListAuthorsResponseDataFromJSONTyped(json, false);
}

export function ListAuthorsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAuthorsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'authors': json['authors'] == null ? undefined : ((json['authors'] as Array<any>).map(AuthorDataFromJSON)),
    };
}

export function ListAuthorsResponseDataToJSON(json: any): ListAuthorsResponseData {
    return ListAuthorsResponseDataToJSONTyped(json, false);
}

export function ListAuthorsResponseDataToJSONTyped(value?: ListAuthorsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authors': value['authors'] == null ? undefined : ((value['authors'] as Array<any>).map(AuthorDataToJSON)),
    };
}

