/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryInfo } from './CategoryInfo';
import {
    CategoryInfoFromJSON,
    CategoryInfoFromJSONTyped,
    CategoryInfoToJSON,
    CategoryInfoToJSONTyped,
} from './CategoryInfo';

/**
 * 
 * @export
 * @interface ListCategoriesResponseData
 */
export interface ListCategoriesResponseData {
    /**
     * 
     * @type {Array<CategoryInfo>}
     * @memberof ListCategoriesResponseData
     */
    categories?: Array<CategoryInfo>;
}

/**
 * Check if a given object implements the ListCategoriesResponseData interface.
 */
export function instanceOfListCategoriesResponseData(value: object): value is ListCategoriesResponseData {
    return true;
}

export function ListCategoriesResponseDataFromJSON(json: any): ListCategoriesResponseData {
    return ListCategoriesResponseDataFromJSONTyped(json, false);
}

export function ListCategoriesResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCategoriesResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(CategoryInfoFromJSON)),
    };
}

export function ListCategoriesResponseDataToJSON(json: any): ListCategoriesResponseData {
    return ListCategoriesResponseDataToJSONTyped(json, false);
}

export function ListCategoriesResponseDataToJSONTyped(value?: ListCategoriesResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(CategoryInfoToJSON)),
    };
}

