/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListLibraryBooksByStatusRequest
 */
export interface ListLibraryBooksByStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof ListLibraryBooksByStatusRequest
     */
    readingStatus: ListLibraryBooksByStatusRequestReadingStatusEnum;
}


/**
 * @export
 */
export const ListLibraryBooksByStatusRequestReadingStatusEnum = {
    InProgress: 'inProgress',
    Finished: 'finished',
    Planned: 'planned'
} as const;
export type ListLibraryBooksByStatusRequestReadingStatusEnum = typeof ListLibraryBooksByStatusRequestReadingStatusEnum[keyof typeof ListLibraryBooksByStatusRequestReadingStatusEnum];


/**
 * Check if a given object implements the ListLibraryBooksByStatusRequest interface.
 */
export function instanceOfListLibraryBooksByStatusRequest(value: object): value is ListLibraryBooksByStatusRequest {
    if (!('readingStatus' in value) || value['readingStatus'] === undefined) return false;
    return true;
}

export function ListLibraryBooksByStatusRequestFromJSON(json: any): ListLibraryBooksByStatusRequest {
    return ListLibraryBooksByStatusRequestFromJSONTyped(json, false);
}

export function ListLibraryBooksByStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListLibraryBooksByStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'readingStatus': json['readingStatus'],
    };
}

export function ListLibraryBooksByStatusRequestToJSON(json: any): ListLibraryBooksByStatusRequest {
    return ListLibraryBooksByStatusRequestToJSONTyped(json, false);
}

export function ListLibraryBooksByStatusRequestToJSONTyped(value?: ListLibraryBooksByStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'readingStatus': value['readingStatus'],
    };
}

