/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookData } from './BookData';
import {
    BookDataFromJSON,
    BookDataFromJSONTyped,
    BookDataToJSON,
    BookDataToJSONTyped,
} from './BookData';

/**
 * 
 * @export
 * @interface ListAuthorBooksResponseData
 */
export interface ListAuthorBooksResponseData {
    /**
     * 
     * @type {Array<BookData>}
     * @memberof ListAuthorBooksResponseData
     */
    books: Array<BookData>;
}

/**
 * Check if a given object implements the ListAuthorBooksResponseData interface.
 */
export function instanceOfListAuthorBooksResponseData(value: object): value is ListAuthorBooksResponseData {
    if (!('books' in value) || value['books'] === undefined) return false;
    return true;
}

export function ListAuthorBooksResponseDataFromJSON(json: any): ListAuthorBooksResponseData {
    return ListAuthorBooksResponseDataFromJSONTyped(json, false);
}

export function ListAuthorBooksResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAuthorBooksResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'books': ((json['books'] as Array<any>).map(BookDataFromJSON)),
    };
}

export function ListAuthorBooksResponseDataToJSON(json: any): ListAuthorBooksResponseData {
    return ListAuthorBooksResponseDataToJSONTyped(json, false);
}

export function ListAuthorBooksResponseDataToJSONTyped(value?: ListAuthorBooksResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'books': ((value['books'] as Array<any>).map(BookDataToJSON)),
    };
}

