/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedbackInfo } from './FeedbackInfo';
import {
    FeedbackInfoFromJSON,
    FeedbackInfoFromJSONTyped,
    FeedbackInfoToJSON,
    FeedbackInfoToJSONTyped,
} from './FeedbackInfo';

/**
 * 
 * @export
 * @interface ListBookFeedbackResponseData
 */
export interface ListBookFeedbackResponseData {
    /**
     * 
     * @type {Array<FeedbackInfo>}
     * @memberof ListBookFeedbackResponseData
     */
    feedback: Array<FeedbackInfo>;
}

/**
 * Check if a given object implements the ListBookFeedbackResponseData interface.
 */
export function instanceOfListBookFeedbackResponseData(value: object): value is ListBookFeedbackResponseData {
    if (!('feedback' in value) || value['feedback'] === undefined) return false;
    return true;
}

export function ListBookFeedbackResponseDataFromJSON(json: any): ListBookFeedbackResponseData {
    return ListBookFeedbackResponseDataFromJSONTyped(json, false);
}

export function ListBookFeedbackResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBookFeedbackResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'feedback': ((json['feedback'] as Array<any>).map(FeedbackInfoFromJSON)),
    };
}

export function ListBookFeedbackResponseDataToJSON(json: any): ListBookFeedbackResponseData {
    return ListBookFeedbackResponseDataToJSONTyped(json, false);
}

export function ListBookFeedbackResponseDataToJSONTyped(value?: ListBookFeedbackResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feedback': ((value['feedback'] as Array<any>).map(FeedbackInfoToJSON)),
    };
}

