/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfo } from './UserInfo';
import {
    UserInfoFromJSON,
    UserInfoFromJSONTyped,
    UserInfoToJSON,
    UserInfoToJSONTyped,
} from './UserInfo';

/**
 * 
 * @export
 * @interface ListUsersResponseData
 */
export interface ListUsersResponseData {
    /**
     * 
     * @type {Array<UserInfo>}
     * @memberof ListUsersResponseData
     */
    users?: Array<UserInfo>;
}

/**
 * Check if a given object implements the ListUsersResponseData interface.
 */
export function instanceOfListUsersResponseData(value: object): value is ListUsersResponseData {
    return true;
}

export function ListUsersResponseDataFromJSON(json: any): ListUsersResponseData {
    return ListUsersResponseDataFromJSONTyped(json, false);
}

export function ListUsersResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUsersResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserInfoFromJSON)),
    };
}

export function ListUsersResponseDataToJSON(json: any): ListUsersResponseData {
    return ListUsersResponseDataToJSONTyped(json, false);
}

export function ListUsersResponseDataToJSONTyped(value?: ListUsersResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserInfoToJSON)),
    };
}

