/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookData } from './BookData';
import {
    BookDataFromJSON,
    BookDataFromJSONTyped,
    BookDataToJSON,
    BookDataToJSONTyped,
} from './BookData';

/**
 * 
 * @export
 * @interface ListBooksResponseData
 */
export interface ListBooksResponseData {
    /**
     * 
     * @type {Array<BookData>}
     * @memberof ListBooksResponseData
     */
    books?: Array<BookData>;
}

/**
 * Check if a given object implements the ListBooksResponseData interface.
 */
export function instanceOfListBooksResponseData(value: object): value is ListBooksResponseData {
    return true;
}

export function ListBooksResponseDataFromJSON(json: any): ListBooksResponseData {
    return ListBooksResponseDataFromJSONTyped(json, false);
}

export function ListBooksResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBooksResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'books': json['books'] == null ? undefined : ((json['books'] as Array<any>).map(BookDataFromJSON)),
    };
}

export function ListBooksResponseDataToJSON(json: any): ListBooksResponseData {
    return ListBooksResponseDataToJSONTyped(json, false);
}

export function ListBooksResponseDataToJSONTyped(value?: ListBooksResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'books': value['books'] == null ? undefined : ((value['books'] as Array<any>).map(BookDataToJSON)),
    };
}

