/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginUserResponseData
 */
export interface LoginUserResponseData {
    /**
     * 
     * @type {string}
     * @memberof LoginUserResponseData
     */
    token: string;
}

/**
 * Check if a given object implements the LoginUserResponseData interface.
 */
export function instanceOfLoginUserResponseData(value: object): value is LoginUserResponseData {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function LoginUserResponseDataFromJSON(json: any): LoginUserResponseData {
    return LoginUserResponseDataFromJSONTyped(json, false);
}

export function LoginUserResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUserResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function LoginUserResponseDataToJSON(json: any): LoginUserResponseData {
    return LoginUserResponseDataToJSONTyped(json, false);
}

export function LoginUserResponseDataToJSONTyped(value?: LoginUserResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

