/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleData } from './ArticleData';
import {
    ArticleDataFromJSON,
    ArticleDataFromJSONTyped,
    ArticleDataToJSON,
    ArticleDataToJSONTyped,
} from './ArticleData';

/**
 * 
 * @export
 * @interface ManagementArticlesResponseData
 */
export interface ManagementArticlesResponseData {
    /**
     * 
     * @type {Array<ArticleData>}
     * @memberof ManagementArticlesResponseData
     */
    articles?: Array<ArticleData>;
}

/**
 * Check if a given object implements the ManagementArticlesResponseData interface.
 */
export function instanceOfManagementArticlesResponseData(value: object): value is ManagementArticlesResponseData {
    return true;
}

export function ManagementArticlesResponseDataFromJSON(json: any): ManagementArticlesResponseData {
    return ManagementArticlesResponseDataFromJSONTyped(json, false);
}

export function ManagementArticlesResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagementArticlesResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'articles': json['articles'] == null ? undefined : ((json['articles'] as Array<any>).map(ArticleDataFromJSON)),
    };
}

export function ManagementArticlesResponseDataToJSON(json: any): ManagementArticlesResponseData {
    return ManagementArticlesResponseDataToJSONTyped(json, false);
}

export function ManagementArticlesResponseDataToJSONTyped(value?: ManagementArticlesResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'articles': value['articles'] == null ? undefined : ((value['articles'] as Array<any>).map(ArticleDataToJSON)),
    };
}

