/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotFoundResponseData
 */
export interface NotFoundResponseData {
    /**
     * 
     * @type {string}
     * @memberof NotFoundResponseData
     */
    code: NotFoundResponseDataCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof NotFoundResponseData
     */
    message: string;
}


/**
 * @export
 */
export const NotFoundResponseDataCodeEnum = {
    NotFound: 'NotFound'
} as const;
export type NotFoundResponseDataCodeEnum = typeof NotFoundResponseDataCodeEnum[keyof typeof NotFoundResponseDataCodeEnum];


/**
 * Check if a given object implements the NotFoundResponseData interface.
 */
export function instanceOfNotFoundResponseData(value: object): value is NotFoundResponseData {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function NotFoundResponseDataFromJSON(json: any): NotFoundResponseData {
    return NotFoundResponseDataFromJSONTyped(json, false);
}

export function NotFoundResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFoundResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function NotFoundResponseDataToJSON(json: any): NotFoundResponseData {
    return NotFoundResponseDataToJSONTyped(json, false);
}

export function NotFoundResponseDataToJSONTyped(value?: NotFoundResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

