/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermissionDeniedResponseData
 */
export interface PermissionDeniedResponseData {
    /**
     * 
     * @type {string}
     * @memberof PermissionDeniedResponseData
     */
    code: PermissionDeniedResponseDataCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof PermissionDeniedResponseData
     */
    message: string;
}


/**
 * @export
 */
export const PermissionDeniedResponseDataCodeEnum = {
    PermissionDenied: 'PermissionDenied'
} as const;
export type PermissionDeniedResponseDataCodeEnum = typeof PermissionDeniedResponseDataCodeEnum[keyof typeof PermissionDeniedResponseDataCodeEnum];


/**
 * Check if a given object implements the PermissionDeniedResponseData interface.
 */
export function instanceOfPermissionDeniedResponseData(value: object): value is PermissionDeniedResponseData {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PermissionDeniedResponseDataFromJSON(json: any): PermissionDeniedResponseData {
    return PermissionDeniedResponseDataFromJSONTyped(json, false);
}

export function PermissionDeniedResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDeniedResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function PermissionDeniedResponseDataToJSON(json: any): PermissionDeniedResponseData {
    return PermissionDeniedResponseDataToJSONTyped(json, false);
}

export function PermissionDeniedResponseDataToJSONTyped(value?: PermissionDeniedResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

