/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveBookFeedbackResponseData
 */
export interface SaveBookFeedbackResponseData {
    /**
     * 
     * @type {number}
     * @memberof SaveBookFeedbackResponseData
     */
    id?: number;
}

/**
 * Check if a given object implements the SaveBookFeedbackResponseData interface.
 */
export function instanceOfSaveBookFeedbackResponseData(value: object): value is SaveBookFeedbackResponseData {
    return true;
}

export function SaveBookFeedbackResponseDataFromJSON(json: any): SaveBookFeedbackResponseData {
    return SaveBookFeedbackResponseDataFromJSONTyped(json, false);
}

export function SaveBookFeedbackResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveBookFeedbackResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function SaveBookFeedbackResponseDataToJSON(json: any): SaveBookFeedbackResponseData {
    return SaveBookFeedbackResponseDataToJSONTyped(json, false);
}

export function SaveBookFeedbackResponseDataToJSONTyped(value?: SaveBookFeedbackResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

