/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookData } from './BookData';
import {
    BookDataFromJSON,
    BookDataFromJSONTyped,
    BookDataToJSON,
    BookDataToJSONTyped,
} from './BookData';

/**
 * 
 * @export
 * @interface SearchBooksResponseData
 */
export interface SearchBooksResponseData {
    /**
     * 
     * @type {Array<BookData>}
     * @memberof SearchBooksResponseData
     */
    books?: Array<BookData>;
}

/**
 * Check if a given object implements the SearchBooksResponseData interface.
 */
export function instanceOfSearchBooksResponseData(value: object): value is SearchBooksResponseData {
    return true;
}

export function SearchBooksResponseDataFromJSON(json: any): SearchBooksResponseData {
    return SearchBooksResponseDataFromJSONTyped(json, false);
}

export function SearchBooksResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchBooksResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'books': json['books'] == null ? undefined : ((json['books'] as Array<any>).map(BookDataFromJSON)),
    };
}

export function SearchBooksResponseDataToJSON(json: any): SearchBooksResponseData {
    return SearchBooksResponseDataToJSONTyped(json, false);
}

export function SearchBooksResponseDataToJSONTyped(value?: SearchBooksResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'books': value['books'] == null ? undefined : ((value['books'] as Array<any>).map(BookDataToJSON)),
    };
}

