/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookData } from './BookData';
import {
    BookDataFromJSON,
    BookDataFromJSONTyped,
    BookDataToJSON,
    BookDataToJSONTyped,
} from './BookData';

/**
 * 
 * @export
 * @interface SearchBooksByOptionResponseData
 */
export interface SearchBooksByOptionResponseData {
    /**
     * 
     * @type {Array<BookData>}
     * @memberof SearchBooksByOptionResponseData
     */
    books?: Array<BookData>;
}

/**
 * Check if a given object implements the SearchBooksByOptionResponseData interface.
 */
export function instanceOfSearchBooksByOptionResponseData(value: object): value is SearchBooksByOptionResponseData {
    return true;
}

export function SearchBooksByOptionResponseDataFromJSON(json: any): SearchBooksByOptionResponseData {
    return SearchBooksByOptionResponseDataFromJSONTyped(json, false);
}

export function SearchBooksByOptionResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchBooksByOptionResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'books': json['books'] == null ? undefined : ((json['books'] as Array<any>).map(BookDataFromJSON)),
    };
}

export function SearchBooksByOptionResponseDataToJSON(json: any): SearchBooksByOptionResponseData {
    return SearchBooksByOptionResponseDataToJSONTyped(json, false);
}

export function SearchBooksByOptionResponseDataToJSONTyped(value?: SearchBooksByOptionResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'books': value['books'] == null ? undefined : ((value['books'] as Array<any>).map(BookDataToJSON)),
    };
}

