/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleData } from './ArticleData';
import {
    ArticleDataFromJSON,
    ArticleDataFromJSONTyped,
    ArticleDataToJSON,
    ArticleDataToJSONTyped,
} from './ArticleData';

/**
 * 
 * @export
 * @interface SearchArticlesResponseData
 */
export interface SearchArticlesResponseData {
    /**
     * 
     * @type {Array<ArticleData>}
     * @memberof SearchArticlesResponseData
     */
    articles: Array<ArticleData>;
    /**
     * 
     * @type {number}
     * @memberof SearchArticlesResponseData
     */
    totalCount: number;
}

/**
 * Check if a given object implements the SearchArticlesResponseData interface.
 */
export function instanceOfSearchArticlesResponseData(value: object): value is SearchArticlesResponseData {
    if (!('articles' in value) || value['articles'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function SearchArticlesResponseDataFromJSON(json: any): SearchArticlesResponseData {
    return SearchArticlesResponseDataFromJSONTyped(json, false);
}

export function SearchArticlesResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchArticlesResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'articles': ((json['articles'] as Array<any>).map(ArticleDataFromJSON)),
        'totalCount': json['totalCount'],
    };
}

export function SearchArticlesResponseDataToJSON(json: any): SearchArticlesResponseData {
    return SearchArticlesResponseDataToJSONTyped(json, false);
}

export function SearchArticlesResponseDataToJSONTyped(value?: SearchArticlesResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'articles': ((value['articles'] as Array<any>).map(ArticleDataToJSON)),
        'totalCount': value['totalCount'],
    };
}

