/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorInfo } from './AuthorInfo';
import {
    AuthorInfoFromJSON,
    AuthorInfoFromJSONTyped,
    AuthorInfoToJSON,
    AuthorInfoToJSONTyped,
} from './AuthorInfo';

/**
 * 
 * @export
 * @interface SearchAuthorsResponseData
 */
export interface SearchAuthorsResponseData {
    /**
     * 
     * @type {Array<AuthorInfo>}
     * @memberof SearchAuthorsResponseData
     */
    authors: Array<AuthorInfo>;
    /**
     * 
     * @type {number}
     * @memberof SearchAuthorsResponseData
     */
    totalCount: number;
}

/**
 * Check if a given object implements the SearchAuthorsResponseData interface.
 */
export function instanceOfSearchAuthorsResponseData(value: object): value is SearchAuthorsResponseData {
    if (!('authors' in value) || value['authors'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function SearchAuthorsResponseDataFromJSON(json: any): SearchAuthorsResponseData {
    return SearchAuthorsResponseDataFromJSONTyped(json, false);
}

export function SearchAuthorsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAuthorsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'authors': ((json['authors'] as Array<any>).map(AuthorInfoFromJSON)),
        'totalCount': json['totalCount'],
    };
}

export function SearchAuthorsResponseDataToJSON(json: any): SearchAuthorsResponseData {
    return SearchAuthorsResponseDataToJSONTyped(json, false);
}

export function SearchAuthorsResponseDataToJSONTyped(value?: SearchAuthorsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authors': ((value['authors'] as Array<any>).map(AuthorInfoToJSON)),
        'totalCount': value['totalCount'],
    };
}

