/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchBooksRequest
 */
export interface SearchBooksRequest {
    /**
     * 
     * @type {string}
     * @memberof SearchBooksRequest
     */
    searchString: string;
}

/**
 * Check if a given object implements the SearchBooksRequest interface.
 */
export function instanceOfSearchBooksRequest(value: object): value is SearchBooksRequest {
    if (!('searchString' in value) || value['searchString'] === undefined) return false;
    return true;
}

export function SearchBooksRequestFromJSON(json: any): SearchBooksRequest {
    return SearchBooksRequestFromJSONTyped(json, false);
}

export function SearchBooksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchBooksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'searchString': json['searchString'],
    };
}

export function SearchBooksRequestToJSON(json: any): SearchBooksRequest {
    return SearchBooksRequestToJSONTyped(json, false);
}

export function SearchBooksRequestToJSONTyped(value?: SearchBooksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'searchString': value['searchString'],
    };
}

