/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchItemsRequest
 */
export interface SearchItemsRequest {
    /**
     * 
     * @type {string}
     * @memberof SearchItemsRequest
     */
    searchString: string;
}

/**
 * Check if a given object implements the SearchItemsRequest interface.
 */
export function instanceOfSearchItemsRequest(value: object): value is SearchItemsRequest {
    if (!('searchString' in value) || value['searchString'] === undefined) return false;
    return true;
}

export function SearchItemsRequestFromJSON(json: any): SearchItemsRequest {
    return SearchItemsRequestFromJSONTyped(json, false);
}

export function SearchItemsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchItemsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'searchString': json['searchString'],
    };
}

export function SearchItemsRequestToJSON(json: any): SearchItemsRequest {
    return SearchItemsRequestToJSONTyped(json, false);
}

export function SearchItemsRequestToJSONTyped(value?: SearchItemsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'searchString': value['searchString'],
    };
}

