/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnauthorizedResponseData
 */
export interface UnauthorizedResponseData {
    /**
     * 
     * @type {string}
     * @memberof UnauthorizedResponseData
     */
    code: UnauthorizedResponseDataCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof UnauthorizedResponseData
     */
    message: string;
}


/**
 * @export
 */
export const UnauthorizedResponseDataCodeEnum = {
    Unauthorized: 'Unauthorized'
} as const;
export type UnauthorizedResponseDataCodeEnum = typeof UnauthorizedResponseDataCodeEnum[keyof typeof UnauthorizedResponseDataCodeEnum];


/**
 * Check if a given object implements the UnauthorizedResponseData interface.
 */
export function instanceOfUnauthorizedResponseData(value: object): value is UnauthorizedResponseData {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UnauthorizedResponseDataFromJSON(json: any): UnauthorizedResponseData {
    return UnauthorizedResponseDataFromJSONTyped(json, false);
}

export function UnauthorizedResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthorizedResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function UnauthorizedResponseDataToJSON(json: any): UnauthorizedResponseData {
    return UnauthorizedResponseDataToJSONTyped(json, false);
}

export function UnauthorizedResponseDataToJSONTyped(value?: UnauthorizedResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

