/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFileResponseData
 */
export interface UploadFileResponseData {
    /**
     * 
     * @type {string}
     * @memberof UploadFileResponseData
     */
    filePath: string;
}

/**
 * Check if a given object implements the UploadFileResponseData interface.
 */
export function instanceOfUploadFileResponseData(value: object): value is UploadFileResponseData {
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    return true;
}

export function UploadFileResponseDataFromJSON(json: any): UploadFileResponseData {
    return UploadFileResponseDataFromJSONTyped(json, false);
}

export function UploadFileResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFileResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'filePath': json['filePath'],
    };
}

export function UploadFileResponseDataToJSON(json: any): UploadFileResponseData {
    return UploadFileResponseDataToJSONTyped(json, false);
}

export function UploadFileResponseDataToJSONTyped(value?: UploadFileResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filePath': value['filePath'],
    };
}

