/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserData
 */
export interface UserData {
    /**
     * 
     * @type {number}
     * @memberof UserData
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserData
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserData
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserData
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserData
     */
    avatarPath?: string;
}

/**
 * Check if a given object implements the UserData interface.
 */
export function instanceOfUserData(value: object): value is UserData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserDataFromJSON(json: any): UserData {
    return UserDataFromJSONTyped(json, false);
}

export function UserDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'username': json['username'],
        'avatarPath': json['avatarPath'] == null ? undefined : json['avatarPath'],
    };
}

export function UserDataToJSON(json: any): UserData {
    return UserDataToJSONTyped(json, false);
}

export function UserDataToJSONTyped(value?: UserData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'username': value['username'],
        'avatarPath': value['avatarPath'],
    };
}

