services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
    command: ["go", "run", "cmd/main.go"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # для разработки
    ports:
      - "5173:5173" # для разработки
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]