/* tslint:disable */
/* eslint-disable */
/**
 * Book Lib public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddBookRequest,
  AddBookResponseData,
  BadRequestResponseData,
  ChangeReadingStatusRequest,
  GetBookInfoResponseData,
  ListBookFeedbackResponseData,
  ListBooksResponseData,
  NotFoundResponseData,
  PermissionDeniedResponseData,
  SaveBookFeedbackRequest,
  SaveBookFeedbackResponseData,
  SearchBooksByOptionResponseData,
  SearchBooksRequest,
  SearchBooksResponseData,
  UnauthorizedResponseData,
} from '../models/index';
import {
    AddBookRequestFromJSON,
    AddBookRequestToJSON,
    AddBookResponseDataFromJSON,
    AddBookResponseDataToJSON,
    BadRequestResponseDataFromJSON,
    BadRequestResponseDataToJSON,
    ChangeReadingStatusRequestFromJSON,
    ChangeReadingStatusRequestToJSON,
    GetBookInfoResponseDataFromJSON,
    GetBookInfoResponseDataToJSON,
    ListBookFeedbackResponseDataFromJSON,
    ListBookFeedbackResponseDataToJSON,
    ListBooksResponseDataFromJSON,
    ListBooksResponseDataToJSON,
    NotFoundResponseDataFromJSON,
    NotFoundResponseDataToJSON,
    PermissionDeniedResponseDataFromJSON,
    PermissionDeniedResponseDataToJSON,
    SaveBookFeedbackRequestFromJSON,
    SaveBookFeedbackRequestToJSON,
    SaveBookFeedbackResponseDataFromJSON,
    SaveBookFeedbackResponseDataToJSON,
    SearchBooksByOptionResponseDataFromJSON,
    SearchBooksByOptionResponseDataToJSON,
    SearchBooksRequestFromJSON,
    SearchBooksRequestToJSON,
    SearchBooksResponseDataFromJSON,
    SearchBooksResponseDataToJSON,
    UnauthorizedResponseDataFromJSON,
    UnauthorizedResponseDataToJSON,
} from '../models/index';

export interface AddBookOperationRequest {
    addBookRequest: AddBookRequest;
}

export interface AddBookToLibraryRequest {
    bookID: number;
}

export interface ChangeReadingStatusOperationRequest {
    bookID: number;
    changeReadingStatusRequest?: ChangeReadingStatusRequest;
}

export interface DeleteBookRequest {
    bookID: number;
}

export interface GetBookInfoRequest {
    bookID: number;
}

export interface ListBookFeedbackRequest {
    bookID: number;
}

export interface SaveBookFeedbackOperationRequest {
    bookID: number;
    saveBookFeedbackRequest?: SaveBookFeedbackRequest;
}

export interface SearchBooksOperationRequest {
    searchBooksRequest: SearchBooksRequest;
}

export interface SearchBooksByOptionRequest {
    body: object;
}

/**
 * 
 */
export class BookApi extends runtime.BaseAPI {

    /**
     */
    async addBookRaw(requestParameters: AddBookOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddBookResponseData>> {
        if (requestParameters['addBookRequest'] == null) {
            throw new runtime.RequiredError(
                'addBookRequest',
                'Required parameter "addBookRequest" was null or undefined when calling addBook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddBookRequestToJSON(requestParameters['addBookRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddBookResponseDataFromJSON(jsonValue));
    }

    /**
     */
    async addBook(requestParameters: AddBookOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddBookResponseData> {
        const response = await this.addBookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async addBookToLibraryRaw(requestParameters: AddBookToLibraryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['bookID'] == null) {
            throw new runtime.RequiredError(
                'bookID',
                'Required parameter "bookID" was null or undefined when calling addBookToLibrary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/{bookID}/library/add`.replace(`{${"bookID"}}`, encodeURIComponent(String(requestParameters['bookID']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async addBookToLibrary(requestParameters: AddBookToLibraryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addBookToLibraryRaw(requestParameters, initOverrides);
    }

    /**
     */
    async changeReadingStatusRaw(requestParameters: ChangeReadingStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['bookID'] == null) {
            throw new runtime.RequiredError(
                'bookID',
                'Required parameter "bookID" was null or undefined when calling changeReadingStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/{bookID}/status`.replace(`{${"bookID"}}`, encodeURIComponent(String(requestParameters['bookID']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeReadingStatusRequestToJSON(requestParameters['changeReadingStatusRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async changeReadingStatus(requestParameters: ChangeReadingStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.changeReadingStatusRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteBookRaw(requestParameters: DeleteBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['bookID'] == null) {
            throw new runtime.RequiredError(
                'bookID',
                'Required parameter "bookID" was null or undefined when calling deleteBook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/{bookID}/delete`.replace(`{${"bookID"}}`, encodeURIComponent(String(requestParameters['bookID']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteBook(requestParameters: DeleteBookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBookRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getBookInfoRaw(requestParameters: GetBookInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBookInfoResponseData>> {
        if (requestParameters['bookID'] == null) {
            throw new runtime.RequiredError(
                'bookID',
                'Required parameter "bookID" was null or undefined when calling getBookInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/{bookID}/info`.replace(`{${"bookID"}}`, encodeURIComponent(String(requestParameters['bookID']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBookInfoResponseDataFromJSON(jsonValue));
    }

    /**
     */
    async getBookInfo(requestParameters: GetBookInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBookInfoResponseData> {
        const response = await this.getBookInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLibraryStatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/library/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async getLibraryStats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getLibraryStatsRaw(initOverrides);
    }

    /**
     */
    async listBookFeedbackRaw(requestParameters: ListBookFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBookFeedbackResponseData>> {
        if (requestParameters['bookID'] == null) {
            throw new runtime.RequiredError(
                'bookID',
                'Required parameter "bookID" was null or undefined when calling listBookFeedback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/{bookID}/feedback/list`.replace(`{${"bookID"}}`, encodeURIComponent(String(requestParameters['bookID']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListBookFeedbackResponseDataFromJSON(jsonValue));
    }

    /**
     */
    async listBookFeedback(requestParameters: ListBookFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBookFeedbackResponseData> {
        const response = await this.listBookFeedbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listBooksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBooksResponseData>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListBooksResponseDataFromJSON(jsonValue));
    }

    /**
     */
    async listBooks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBooksResponseData> {
        const response = await this.listBooksRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async saveBookFeedbackRaw(requestParameters: SaveBookFeedbackOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaveBookFeedbackResponseData>> {
        if (requestParameters['bookID'] == null) {
            throw new runtime.RequiredError(
                'bookID',
                'Required parameter "bookID" was null or undefined when calling saveBookFeedback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/{bookID}/feedback`.replace(`{${"bookID"}}`, encodeURIComponent(String(requestParameters['bookID']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveBookFeedbackRequestToJSON(requestParameters['saveBookFeedbackRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaveBookFeedbackResponseDataFromJSON(jsonValue));
    }

    /**
     */
    async saveBookFeedback(requestParameters: SaveBookFeedbackOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaveBookFeedbackResponseData> {
        const response = await this.saveBookFeedbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async searchBooksRaw(requestParameters: SearchBooksOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchBooksResponseData>> {
        if (requestParameters['searchBooksRequest'] == null) {
            throw new runtime.RequiredError(
                'searchBooksRequest',
                'Required parameter "searchBooksRequest" was null or undefined when calling searchBooks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchBooksRequestToJSON(requestParameters['searchBooksRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchBooksResponseDataFromJSON(jsonValue));
    }

    /**
     */
    async searchBooks(requestParameters: SearchBooksOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchBooksResponseData> {
        const response = await this.searchBooksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async searchBooksByOptionRaw(requestParameters: SearchBooksByOptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchBooksByOptionResponseData>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling searchBooksByOption().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/book/search/option`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchBooksByOptionResponseDataFromJSON(jsonValue));
    }

    /**
     */
    async searchBooksByOption(requestParameters: SearchBooksByOptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchBooksByOptionResponseData> {
        const response = await this.searchBooksByOptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
